/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quickstone_win32_NTService */

#ifndef _Included_com_quickstone_win32_NTService
#define _Included_com_quickstone_win32_NTService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_quickstone_win32_NTService
 * Method:    startDispatcher
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_quickstone_win32_NTService_startDispatcher
  (JNIEnv *, jobject);

/*
 * Class:     com_quickstone_win32_NTService
 * Method:    waitForStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_quickstone_win32_NTService_waitForStart
  (JNIEnv *, jobject);

/*
 * Class:     com_quickstone_win32_NTService
 * Method:    waitForStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_quickstone_win32_NTService_waitForStop
  (JNIEnv *, jobject);

/*
 * Class:     com_quickstone_win32_NTService
 * Method:    acknowledgeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_quickstone_win32_NTService_acknowledgeStop
  (JNIEnv *, jobject);

/*
 * Class:     com_quickstone_win32_NTService
 * Method:    prepareSemaphores
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_quickstone_win32_NTService_prepareSemaphores
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
